version: 2
executorType: docker
containerInfo:
  - image: chrisdoc/android_ci:latest
stages:
  build:
    workDir: /tmp/finstergram
    steps:
      - type: checkout
      - type: shell
        name: "Gradle version"
        command: |
          sdkmanager --list
          ./gradlew --version
      - type: shell
        name: "Run tests"
        command: |
          source environmentSetup.sh && copyEnvVarsToGradleProperties
          ./gradlew clean test
      - type: test-results-store
        path: /tmp/test-results
