version: 2
executorType: docker
containerInfo:
  - image: beevelop/java:latest
stages:
  build:
    workDir: .
    steps:
      - type: shell
        name: "Install git"
        command: |
          apt-get update
          apt-get -qq install git
      - type: checkout
      - type: shell
        name: "Gradle version"
        command: |
          ./gradlew --version
      - type: shell
        name: "Run tests"
        command: |
          source environmentSetup.sh && copyEnvVarsToGradlePropertiesu
          ./gradlew clean test
      - type: test-results-store
        path: /tmp/test-results
